package fileset

// corporateProfile returns the built-in corporate fileset profile.
func corporateProfile() Profile {
	return Profile{
		Name:        "corporate",
		Description: "Corporate share with finance, engineering, legal, marketing, and shared operations data.",
		Directories: []string{
			"Documents/Policies", "Documents/Templates", "Documents/Manuals", "Documents/Drafts",
			"Finance/Reports/2024/Q1", "Finance/Reports/2024/Q2", "Finance/Reports/2024/Q3",
			"Finance/Reports/2024/Q4", "Finance/Reports/2025/Q1", "Finance/Invoices/2024",
			"Finance/Invoices/2025", "Finance/Budgets", "Finance/Receipts",
			"Engineering/CAD/Assemblies", "Engineering/CAD/Parts", "Engineering/Specs",
			"Engineering/Source/backend", "Engineering/Source/frontend", "Engineering/Source/libs",
			"Engineering/Diagrams", "Marketing/Assets/Images/Product", "Marketing/Assets/Images/Social",
			"Marketing/Assets/Images/Web", "Marketing/Assets/Videos/Promo", "Marketing/Assets/Videos/Tutorials",
			"Marketing/Campaigns/2024", "Marketing/Campaigns/2025", "Marketing/Presentations",
			"Marketing/Branding", "HR/Records/Active", "HR/Records/Archived", "HR/Policies",
			"HR/Training/Materials", "HR/Training/Certifications", "HR/Benefits", "IT/Backups/Daily",
			"IT/Backups/Weekly", "IT/Backups/Monthly", "IT/Configs/Servers", "IT/Configs/Network",
			"IT/Scripts", "IT/Logs/Application", "IT/Logs/System", "IT/Logs/Security", "IT/Patches",
			"Media/Photos/2024/Events", "Media/Photos/2024/Products", "Media/Photos/2025",
			"Media/Videos/Raw", "Media/Videos/Edited", "Media/Audio/Recordings", "Media/Audio/Music",
			"Projects/Alpha/docs", "Projects/Alpha/data", "Projects/Beta/docs", "Projects/Beta/data",
			"Projects/Gamma/docs", "Projects/Gamma/data", "Projects/Delta/docs", "Projects/Delta/data",
			"Projects/Epsilon/docs", "Projects/Epsilon/data", "Archives/2022", "Archives/2023", "Archives/2024",
			"Shared/Team-A", "Shared/Team-B", "Shared/Team-C", "Shared/Team-D", "Shared/Public", "Shared/Templates",
			"Databases/Exports", "Databases/Backups", "Databases/Scripts", "Legal/Contracts/Active",
			"Legal/Contracts/Expired", "Legal/Compliance", "Legal/Patents", "Research/Papers",
			"Research/Data/Raw", "Research/Data/Processed", "Research/Presentations", "Operations/Procedures",
			"Operations/Reports", "Operations/Schedules", "Customer/Feedback", "Customer/Support/Tickets",
			"Customer/Support/Logs",
		},
		Nouns: []string{
			"report", "memo", "letter", "proposal", "summary", "notes", "minutes", "agenda",
			"handbook", "guide", "manual", "policy", "procedure", "plan", "review", "brief",
			"whitepaper", "charter", "specification", "requirements", "analysis", "assessment",
			"engineering", "marketing", "finance", "hr", "legal", "operations", "sales", "support",
			"it", "research", "alpha", "beta", "gamma", "delta", "epsilon", "phoenix", "atlas", "nova",
			"apex", "titan", "jsmith", "jdoe", "bwilson", "amartin", "cjones", "klee", "rgarcia",
		},
		Prefixes: []string{"draft", "final", "revised", "updated", "approved", "confidential", "internal", "quarterly", "annual", "monthly"},
		Extensions: map[string][]string{
			"archive": {".zip", ".tar.gz", ".7z", ".rar", ".bz2", ".tgz"},
			"audio":   {".mp3", ".wav", ".flac", ".aac", ".ogg"},
			"code":    {".xml", ".json", ".yaml", ".yml", ".conf", ".ini", ".sh", ".py", ".sql", ".java", ".cpp", ".h", ".go", ".rs", ".js", ".ts", ".css", ".html"},
			"db":      {".db", ".sqlite", ".bak", ".dump", ".sql"},
			"doc":     {".txt", ".doc", ".docx", ".pdf", ".odt", ".rtf", ".md", ".tex"},
			"img":     {".jpg", ".jpeg", ".png", ".bmp", ".tiff", ".gif", ".svg", ".webp", ".ico"},
			"log":     {".log", ".out", ".err"},
			"misc":    {".dat", ".bin", ".tmp", ".bak", ".old", ".iso"},
			"pres":    {".pptx", ".ppt", ".key"},
			"sheet":   {".csv", ".xlsx", ".xls", ".tsv"},
			"vid":     {".mp4", ".avi", ".mov", ".mkv", ".wmv", ".webm"},
		},
		CategoryWeights: map[string]float64{
			"img":     0.25,
			"vid":     0.15,
			"doc":     0.15,
			"sheet":   0.10,
			"archive": 0.10,
			"code":    0.10,
			"audio":   0.05,
			"log":     0.05,
			"misc":    0.05,
		},
		DirectoryRules: []DirectoryRule{
			{Keywords: []string{"Documents", "Policies", "Manuals", "Legal", "Drafts"}, Category: "doc"},
			{Keywords: []string{"Finance", "Budgets", "Receipts"}, Category: "sheet"},
			{Keywords: []string{"Photos", "Images", "Branding"}, Category: "img"},
			{Keywords: []string{"Videos", "Promo", "Tutorials"}, Category: "vid"},
			{Keywords: []string{"Archives", "Backups"}, Category: "archive"},
			{Keywords: []string{"Source", "Scripts", "Configs", "Patches"}, Category: "code"},
			{Keywords: []string{"Logs"}, Category: "log"},
			{Keywords: []string{"Databases"}, Category: "db"},
			{Keywords: []string{"Presentations"}, Category: "pres"},
			{Keywords: []string{"Audio", "Music", "Recordings"}, Category: "audio"},
		},
		SizeTiers: []SizeTier{
			{Name: "tiny", Weight: 40000, MinBytes: 64, MaxBytes: 4 * 1024},
			{Name: "small", Weight: 30000, MinBytes: 4 * 1024, MaxBytes: 64 * 1024},
			{Name: "medium", Weight: 20000, MinBytes: 64 * 1024, MaxBytes: 512 * 1024},
			{Name: "large", Weight: 18000, MinBytes: 128 * 1024, MaxBytes: 512 * 1024},
			{Name: "xl", Weight: 10000, MinBytes: 128 * 1024, MaxBytes: 256 * 1024},
			{Name: "xxl", Weight: 4000, MinBytes: 256 * 1024, MaxBytes: 1024 * 1024},
			{Name: "huge", Weight: 1456, MinBytes: 512 * 1024, MaxBytes: 2 * 1024 * 1024},
		},
	}
}
